Suppress some lints that trigger don't trigger in all cfg's
Alexhuszagh/rust-lexical pull request #83
Opened 2022-05-14 22:10 UTC by Xiphoseer

This `allows` a new nightly lint (rust-lang/rust#96150) on some macros that trigger because of how they interact with `cfg` attributes. From my point-of-view, it didn't make sense to replicate those `cfg` in an `cfg_attr` here. There's another case in my [`patch-5`](https://github.com/Alexhuszagh/rust-lexical/commit/0c1fc32370af22450c182ec853dc270de2261e8c) branch, which might not be a false-positive like these ones.

2022-05-14 22:47 UTC, Alexhuszagh commented
The issue is`allow(unused_macro_rules)` should produce a warning of `unknown_lints` if `cond` is true on anything under `nightly-2022-05-12`, but should work on `nightly-2022-05-12` and above. This means we need some more complex logic, IE, `allow(unknown_lints, unused_macro_rules)`, which I believe I've partially committed as of effaae863913b2f78e6d4ec0fb4fc6fac72637d1.

https://github.com/Alexhuszagh/rust-lexical/blob/effaae863913b2f78e6d4ec0fb4fc6fac72637d1/lexical-benchmark/input.rs#L5

2022-05-14 22:51 UTC, Alexhuszagh requested changes
Please replace the `#[allow(unused_macros)]` changes to also allow `unknown_lints`, or `#[allow(unknown_lints, unused_macros)]`.

Also please rebase to make sure `input.rs` doesn't have any conflicts, since I just submitted a similar patch to that file.

2022-05-14 22:51 UTC, Alexhuszagh commented on lexical-benchmark/input.rs
> +#[allow(unused_macro_rules)]
This won't work on older nightly or stable versions without producing an error of an unknown lint. I get no warning with `rustc 1.62.0-nightly (a5ad0d29a 2022-05-12)`, but I do get a warning with `rustc 1.62.0-nightly (6dd68402c 2022-05-11)`.

2022-05-14 22:51 UTC, Alexhuszagh commented on lexical-parse-float/src/index.rs
> +#[allow(unused_macro_rules)]
Same issue with `unknown_lints` as above.

2022-05-16 15:50 UTC, Alexhuszagh commented
@Xiphoseer I'm planning a release this Wednesday to fix a bug present in #84 in the float writer, so I was wondering if these changes could be made prior to then to ensure no spurious warnings are present.

2022-05-16 22:41 UTC, Alexhuszagh approved these changes

2022-05-16 22:41 UTC, merged

2022-05-16 23:02 UTC, Xiphoseer commented
Right, I totally forgot about `unknown_lints` and that it would affect `stable` and other nightlies. I had looked at https://github.com/dtolnay/syn/commit/189c60c649c42583a98cf39568524e92d9f22524 and didn't realize that this only doesn't need `unknown_lints` because it's just tests.

I've run the CI checks locally before submitting and they all went through. It looks to me like no CI check actually runs something like `RUSTFLAGS=-Dwarnings cargo +stable check`. If I run that on the old commit, it obviously errors out. Might be useful to add that as a non-required job.

Also noticed something weird while testing this: The `unknown_lints` lint doesn't seem to pick up lints within a `cfg_attr` at all times, filed rust-lang/rust#97094 for that just now. So with this PR merged, I don't think any of them will error, but the ones in https://github.com/Alexhuszagh/rust-lexical/blob/0cf23c86694105d02a2bfcfda6bcdae1cd735423/lexical-benchmark/input.rs#L5 and https://github.com/Alexhuszagh/rust-lexical/blob/0cf23c86694105d02a2bfcfda6bcdae1cd735423/lexical-write-integer/src/index.rs#L8 are now somewhat redundant and I should have removed the two in https://github.com/Alexhuszagh/rust-lexical/blob/0cf23c86694105d02a2bfcfda6bcdae1cd735423/lexical-parse-float/src/index.rs#L19 and https://github.com/Alexhuszagh/rust-lexical/blob/0cf23c86694105d02a2bfcfda6bcdae1cd735423/lexical-parse-float/src/index.rs#L36 because you removed the entire macro branch earlier.

2022-05-16 23:21 UTC, Alexhuszagh commented
> Right, I totally forgot about `unknown_lints` and that it would affect `stable` and other nightlies. I had looked at [dtolnay/syn@189c60c](https://github.com/dtolnay/syn/commit/189c60c649c42583a98cf39568524e92d9f22524) and didn't realize that this only doesn't need `unknown_lints` because it's just tests.
> 
> I've run the CI checks locally before submitting and they all went through. It looks to me like no CI check actually runs something like `RUSTFLAGS=-Dwarnings cargo +stable check`. If I run that on the old commit, it obviously errors out. Might be useful to add that as a non-required job.
> 
> Also noticed something weird while testing this: The `unknown_lints` lint doesn't seem to pick up lints within a `cfg_attr` at all times, filed [rust-lang/rust#97094](https://github.com/rust-lang/rust/issues/97094) for that just now. So with this PR merged, I don't think any of them will error, but the one in
> 
> https://github.com/Alexhuszagh/rust-lexical/blob/0cf23c86694105d02a2bfcfda6bcdae1cd735423/lexical-benchmark/input.rs#L5
> is now redundant, the one in
> 
> https://github.com/Alexhuszagh/rust-lexical/blob/0cf23c86694105d02a2bfcfda6bcdae1cd735423/lexical-write-integer/src/index.rs#L8
> should error on stable but doesn't and is also duplicate, and I should have removed the two in
> 
> https://github.com/Alexhuszagh/rust-lexical/blob/0cf23c86694105d02a2bfcfda6bcdae1cd735423/lexical-parse-float/src/index.rs#L19
> and
> 
> https://github.com/Alexhuszagh/rust-lexical/blob/0cf23c86694105d02a2bfcfda6bcdae1cd735423/lexical-parse-float/src/index.rs#L36
> because you removed the entire macro branch earlier.

Incredible work, thank you for all your help with this.